import { setupLayouts } from "virtual:generated-layouts";
import { createRouter, createWebHistory } from "vue-router";
import { routes as autoGeneratedRoutes } from "vue-router/auto-routes";
import type { RouteRecordRaw } from "vue-router";
import { useStateStore } from "@/stores/states";

const indexRoute = autoGeneratedRoutes.find((route) => route.name === "/");
const indexComponent = indexRoute?.component;

// 创建完整的路由数组
const allRoutes = [
  ...autoGeneratedRoutes,
{
  path: "/",
  redirect: "/login",
},
  {
    path: "/:user",
    name: "conversation",
    component: indexComponent,
    props: true,
    meta: { ...(indexRoute?.meta || {}), requiresAuth: true },
  },
  {
    path: "/:user/:session_id",
    name: "session",
    component: indexComponent,
    props: true,
    meta: { ...(indexRoute?.meta || {}), requiresAuth: true },
  },
];

console.log(allRoutes);

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: setupLayouts(allRoutes as RouteRecordRaw[]),
});


router.onError((err, to) => {
  if (err?.message?.includes?.("Failed to fetch dynamically imported module")) {
    if (!localStorage.getItem("vuetify:dynamic-reload")) {
      console.log("Reloading page to fix dynamic import error");
      localStorage.setItem("vuetify:dynamic-reload", "true");
      location.assign(to.fullPath);
    } else {
      console.error("Dynamic import error, reloading page did not fix it", err);
    }
  } else {
    console.error(err);
  }
});

router.isReady().then(() => {
  localStorage.removeItem("vuetify:dynamic-reload");
});

export default router;
