/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    ContactUs: typeof import('./components/ContactUs.vue')['default']
    Conversation: typeof import('./components/Conversation.vue')['default']
    DocumentsManage: typeof import('./components/DocumentsManage.vue')['default']
    MessageAction: typeof import('./components/MessageAction.vue')['default']
    MsgAlert: typeof import('./components/MsgAlert.vue')['default']
    MsgContent: typeof import('./components/MsgContent.vue')['default']
    MsgEditor: typeof import('./components/MsgEditor.vue')['default']
    NavigationDrawer: typeof import('./components/NavigationDrawer.vue')['default']
    Prompt: typeof import('./components/Prompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./components/SettingsDialog.vue')['default']
    UserAvatar: typeof import('./components/UserAvatar.vue')['default']
    UserFooter: typeof import('./components/UserFooter.vue')['default']
    Welcome: typeof import('./components/Welcome.vue')['default']
    WelcomeCard: typeof import('./components/WelcomeCard.vue')['default']
  }
}
